version: '3.9'

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    stop_signal: SIGINT
    volumes:
      - .:/app
    env_file:
      - ./src/config/.env
    ports:
      - 3333:3333
    environment:
      - PORT=3333
    command: npm start